matrix:
  include:
    - language: python
      python: 2.7
      install:
        - pip install -r requirements.txt
      script:
        - python src/scripts/backgroundUpdate.py
        - python src/scripts/BlogReport.py
        - python src/scripts/FinanceReport.py

    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
        - echo "skipping tests"
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token  # Set in the settings page of your repository, as a secure variable
        local_dir: build
        on:
          branch: master
