language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - python3 src/scripts/BlogReport.py
  - echo "skipping tests"
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token  # Set in the settings page of your repository, as a secure variable
  local_dir: build
  on:
    branch: master
