language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - echo "skipping tests"
  - npm run build
  - npm run deploy

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master
